coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "lib/formed/associations"  # ignore folders and all its contents
  - "lib/formed/reflection.rb"
