name: ci

on: [push, pull_request]

env:
  CI: "true"
  RAILS_ENV: "test"

jobs:
  rspec-test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Bundle
        run: |
          gem install bundler -v 2.1.3
          bundle install --jobs 4 --retry 3
      - name: Build and test with rspec
        run: bundle exec rspec
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
